# GitHub Sponsorship Button Configuration
github: [mathcal-S]
custom: ["https://buymeacoffee.com/mathcalS"] # Placeholder for a custom link
# Creativity is fueled by:
patreon: mathcal-S # Placeholder
ko_fi: mathcal-S # Placeholder
